version: '3.2'

services:
  db:
    build: ./postgres/.
    ports:
      - "6432:5432"
      - "122:22"
    volumes:
      - ./data/postgresdatabase/db/data:/var/lib/postgresql/data
      - ./data/postgresdatabase/archive:/archive
    command:
      - "postgres"
      - "-c"
      - "wal_level=hot_standby"
      - "-c"
      - "port=5432"
      - "-c"
      - "hba_file=/var/lib/postgresql/config/pg_hba.conf"
      - "-c"
      - "archive_mode=on"
      - "-c"
      - "archive_command=test ! -f /archive/%f && cp %p /archive/%f"
      - "-c"
      - "max_wal_senders=2"
      - "-c"
      - "max_replication_slots=2"
